### ISSUE TITLE
Not logging in now

### ISSUE THREAD

**Issue by syspic** [tulir/fbchat-asyncio#18]
I had a script that essentially logged all my messenger traffic to a file so I could do some simple analysis on it later. However every now and then it would break so I would have to restart it. That was no issue 

I just tried to make it use a session cookie but that wasn't working and I tried to change it back (I wasn't using version control :'( ) but now it wont log in

This is the error I get in the log file 

```
 INFO: Exited state disconnected
 INFO: Entered state disconnected
 WARNING: Connection rejected with code '3'
 WARNING: Reconnection attempt failed: ConnectException('Connection rejected by broker',)
```

I also get this

```
ERROR: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x75787f30>
ERROR: Fatal write error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x74d84c70>
transport: <_SelectorSocketTransport fd=8 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 761, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

```

On my console I get 

```
Traceback (most recent call last):
  File "test.py", line 143, in start
    await client.listen()
TypeError: object NoneType can't be used in 'await' expression
```

I am doing this

```
    client = OnX(loop=loop, log=XLog) # XLog is my logging definition 
    await client.start(email,pw)

```

**Comment by syspic** [comment]
update: When it _does_ log in I get this error in the log


```
 ERROR: Fatal error listening on MQTT
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.6/site-packages/fbchat/_client.py", line 2940, in _try_listen_mqtt
    await self._listen_mqtt()
  File "/home/pi/.local/lib/python3.6/site-packages/fbchat/_client.py", line 2760, in _listen_mqtt
    self._last_seq_id = int(j["viewer"]["message_threads"]["sync_sequence_id"])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
 ERROR: Fatal error listening
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.6/site-packages/fbchat/_client.py", line 2946, in _try_listen
    await self._listen()
  File "/home/pi/.local/lib/python3.6/site-packages/fbchat/_client.py", line 2924, in _listen
    while await self._do_one_listen():
  File "/home/pi/.local/lib/python3.6/site-packages/fbchat/_client.py", line 2743, in _do_one_listen
    raise e
  File "/home/pi/.local/lib/python3.6/site-packages/fbchat/_client.py", line 2726, in _do_one_listen
    await self._ping()
  File "/home/pi/.local/lib/python3.6/site-packages/fbchat/_client.py", line 2041, in _ping
    data,
  File "/home/pi/.local/lib/python3.6/site-packages/fbchat/_client.py", line 112, in _get
    req_log=self._req_log, util_log=self._util_log)
  File "/home/pi/.local/lib/python3.6/site-packages/fbchat/_state.py", line 228, in _get
    content = await _util.check_request(resp)
  File "/home/pi/.local/lib/python3.6/site-packages/fbchat/_util.py", line 122, in check_request
    check_http_code(r.status)
  File "/home/pi/.local/lib/python3.6/site-packages/fbchat/_util.py", line 137, in check_http_code
    raise FBchatFacebookError(msg, request_status_code=code)
fbchat._exception.FBchatFacebookError: Error when sending request: Got 400 response.
 ERROR: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x75716390>
 ERROR: Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x75720768>, 1646022.412183501)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x74e0d030>, 1646041.02095572), (<aiohttp.client_proto.ResponseHandler object at 0x757209d0>, 1646041.372207645)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x74283bc8>, 1646041.093519068)]']
connector: <aiohttp.connector.TCPConnector object at 0x75716410>

```

**Comment by syspic** [comment]
nvm for some reason you don't need `await` before the `listen` anymore 🤔
