### ISSUE TITLE
TypeError: object str can't be used in 'await' expression

### ISSUE THREAD

**Issue by powerjungle** [tulir/fbchat-asyncio#29]
## Description of the problem
When running a simple login script I'm getting the error in the title.

## Code to reproduce
```py
import getpass
import fbchat
import asyncio

async def main():
    session = await fbchat.Session.login(
        "fabsidereal@gmail.com",
        getpass.getpass(),
        lambda: getpass.getpass("2FA code"),
    )
    
    await session.logout()

asyncio.run(main())

```

## Traceback
```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "test.py", line 9, in main
    lambda: getpass.getpass("2FA code"),
  File "/home/powerjungle/.local/lib/python3.7/site-packages/fbchat/_session.py", line 435, in login
    url = await two_factor_helper(session, r, on_2fa_callback)
  File "/home/powerjungle/.local/lib/python3.7/site-packages/fbchat/_session.py", line 228, in two_factor_helper
    data["approvals_code"] = await on_2fa_callback()
TypeError: object str can't be used in 'await' expression
```

## Environment information
- Python version 3.7
- `fbchat` version 0.6.21

**Comment by tulir** [comment]
The 2fa callback has to be an async method

**Comment by powerjungle** [comment]
Can you give me an example please?
