### ISSUE TITLE
MQTT message parse error

### ISSUE THREAD

**Issue by lanSs** [tulir/fbchat-asyncio#9]
## Description of the problem
Unable to parse MQTT message.

## Code to reproduce
I'm using the latest `mautrix-faceboot` bridge: `0.1.0.dev14` 

## Traceback
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/fbchat/_client.py", line 2874, in _try_parse_mqtt
    await self._parse_mqtt(event_type, event_data)
  File "/usr/lib/python3.7/site-packages/fbchat/_client.py", line 2882, in _parse_mqtt
    delta.get("lastIssuedSeqId") or delta.get("irisSeqId") or 0)
TypeError: '>' not supported between instances of 'str' and 'int'
```

## Environment information
Docker envrionment: `dock.mau.dev/tulir/mautrix-facebook:latest`

This is the message which produces the traceback:
```
{
	'deltas': [{
		'attachments': [],
		'body': 'REDACTED',
		'irisSeqId': 'REDACTED',
		'irisTags': ['DeltaNewMessage', 'is_from_iris_fanout'],
		'messageMetadata': {
			'actorFbId': 'REDACTED',
			'folderId': {
				'systemFolderId': 'INBOX'
			},
			'messageId': 'REDACTED',
			'offlineThreadingId': 'REDACTED',
			'skipBumpThread': False,
			'tags': ['source:chat:orca', 'app_id:REDACTED', 'hot_emoji_size:small'],
			'threadKey': {
				'threadFbId': 'REDACTED'
			},
			'threadReadStateEffect': 'MARK_UNREAD',
			'timestamp': '1574614460384'
		},
		'participants': ['REDACTED', 'REDACTED'],
		'requestContext': {
			'apiArgs': {}
		},
		'tqSeqId': '124412',
		'class': 'NewMessage'
	}],
	'firstDeltaSeqId': REDACTED,
	'lastIssuedSeqId': REDACTED,
	'queueEntityId': REDACTED
}
```

**Comment by tulir** [comment]
I'm pretty sure this was already fixed, are you sure you're using the latest version?

**Comment by lanSs** [comment]
Thank you, downloaded the latest and it works.

Even if I downloaded the docker images few hours ago, it was not the latest.

<img width="748" alt="Screen Shot 2019-11-24 at 2 37 54 PM" src="https://user-images.githubusercontent.com/1125745/69500340-3b569700-0ec8-11ea-92ad-dad4559beca9.png">
